/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_terms` VALUES
(1,"Uncategorized","uncategorized",0),
(2,"chattogram","chattogram",0),
(3,"Dhaka","dhaka",0),
(4,"Khulna","khulna",0),
(5,"Rajshahi","rajshahi",0),
(6,"post-format-image","post-format-image",0),
(7,"post-format-video","post-format-video",0),
(8,"post-format-audio","post-format-audio",0),
(9,"weather","weather",0),
(10,"blog","blog",0),
(11,"finance","finance",0),
(12,"main_menu","main_menu",0),
(13,"social_links","social_links",0),
(14,"post-format-quote","post-format-quote",0),
(16,"One more","one-more",0),
(17,"post-format-link","post-format-link",0),
(18,"Top Menu","top-menu",0),
(19,"post-format-gallery","post-format-gallery",0),
(20,"Color","color",0),
(21,"Nature","nature",0),
(22,"Noposts","noposts",0),
(23,"Footer Left Menu","footer-left-menu",0),
(24,"Footer Middle Menu","footer-middle-menu",0),
(25,"Footer Right Menu","footer-right-menu",0),
(26,"English","english",0),
(27,"Bangla","bangla",0),
(28,"French","french",0);
